version: '3.9'

services:
  crud:
    image: postgres
    container_name: my-db
    restart: always
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
